use_default_settings: true

server:
  secret_key: "ultrasecretkey"

search:
  formats:
    - html
    - json

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'

default_doi_resolver: 'oadoi.org'

