use_default_settings: true

server:
  secret_key: "b29a4d6e8f1c3a5b7d9e2f4c6a8b0d2e4f6c8a0b2d4e6f8c0a2b4d6e8f0c2a4"

search:
  formats:
    - html
    - json

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'

default_doi_resolver: 'oadoi.org'

